const {PGlite}=require(process.env.PGLITE_PATH||'@electric-sql/pglite');
const fs=require('fs'),assert=require('assert/strict');
(async()=>{const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table schools(id uuid primary key default gen_random_uuid(),name text,city text,region text,address text,country_code text,source_type text,source_url text,verified_at timestamptz);
create table teachers(id uuid primary key default gen_random_uuid(),school_id uuid,name text,subject text,category text,initials text,bio text,rating numeric,review_count int,recommend_percent int,source_type text,source_url text,verified_at timestamptz,verification_status text,verification_method text,verification_confidence numeric,verification_checked_at timestamptz);
create table teacher_requests(id uuid,user_id uuid,school_id uuid,region text,city text,school_name text,teacher_name text,subject text,source_url text,status text,candidate_key text,created_at timestamptz);
create function finalize_teacher_verification(uuid,text,text,numeric,jsonb) returns void language sql as $$select$$;
insert into auth.users values('00000000-0000-0000-0000-000000000001'),('00000000-0000-0000-0000-000000000002');
grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;`);
await db.exec(fs.readFileSync(require('path').join(__dirname,'../supabase/migrations/20261008_catalog_requests.sql'),'utf8'));
await db.exec(`set role authenticated;set request.jwt.claim.sub='00000000-0000-0000-0000-000000000001'`);
const args=`'school',null,'Москва','Москва','Школа тест',null,null,null,null`;
const a=(await db.query(`select (submit_catalog_request(${args})).*`)).rows[0];assert.equal(a.status,'queued');
const b=(await db.query(`select (submit_catalog_request(${args})).*`)).rows[0];assert.equal(a.id,b.id);
await assert.rejects(db.query(`select moderate_catalog_request('${a.id}','verified','Проверено по реестру')`),/Доступ/);
await assert.rejects(db.query(`insert into catalog_moderators(user_id) values(auth.uid())`),/permission/);
await db.exec(`reset role;insert into catalog_moderators(user_id) values('00000000-0000-0000-0000-000000000002');set role authenticated;set request.jwt.claim.sub='00000000-0000-0000-0000-000000000002'`);
assert.equal((await db.query('select count(*)::int as n from catalog_requests')).rows[0].n,1);
const published=(await db.query(`select (moderate_catalog_request('${a.id}','verified','Проверено по реестру')).*`)).rows[0];assert.equal(published.status,'published');
await db.exec(`set request.jwt.claim.sub='00000000-0000-0000-0000-000000000001'`);
const t=(await db.query(`select (submit_catalog_request('teacher','${published.school_id}',null,null,null,null,'Иван Петров','Математика',null)).*`)).rows[0];
await db.exec(`set request.jwt.claim.sub='00000000-0000-0000-0000-000000000002'`);
await db.query(`select moderate_catalog_request('${t.id}','verified','Сведения учителя проверены')`);
await db.exec('reset role');assert.equal((await db.query('select rating from teachers')).rows[0].rating,'0');
await assert.rejects(db.query(`select submit_catalog_request('teacher','${published.school_id}',null,null,null,null,'Иван Петров',null,null)`),/check constraint/);
console.log('SQL: identity, deduplication, moderator authorization, RLS, publication without fake ratings, required fields passed');await db.close();})().catch(e=>{console.error(e.message);process.exitCode=1});
